# Generated by Django 2.2.5 on 2021-10-06 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=255)),
                ('release_date', models.DateField(auto_now_add=True)),
                ('straming_url', models.URLField(default='www.test.com')),
                ('channel_logo', models.FileField(blank=True, upload_to='channel_logo')),
            ],
        ),
        migrations.CreateModel(
            name='Channel_catgory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=255)),
                ('release_date', models.DateField(auto_now_add=True)),
                ('cat_slug', models.SlugField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Featrued_Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('channelfetured', models.ManyToManyField(to='Data_app.Add_Channel')),
            ],
        ),
        migrations.AddField(
            model_name='add_channel',
            name='catgory',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Data_app.Channel_catgory'),
        ),
    ]
