# Generated by Django 2.2.5 on 2021-10-06 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featrued_channel',
            old_name='channelfetured',
            new_name='Featrued_Channel',
        ),
    ]
